# Generated by Django 3.2.12 on 2023-01-28 07:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(max_length=60)),
                ('desc', models.TextField()),
                ('discount_percent', models.FloatField()),
                ('modified_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=60)),
                ('desc', models.TextField()),
                ('shop', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(max_length=60)),
                ('desc', models.TextField()),
                ('modified_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='product_inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('quantity', models.IntegerField()),
                ('modified_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('HSN_SAC', models.CharField(max_length=150)),
                ('inventory', models.IntegerField()),
                ('price', models.FloatField()),
                ('MRP', models.FloatField()),
                ('is_curated', models.BooleanField(default=False)),
                ('invoice', models.IntegerField()),
                ('modified_at', models.DateTimeField(default=datetime.datetime.now)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ae.product_category')),
                ('discount_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ae.discount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
