# Generated by Django 3.2.12 on 2023-01-29 06:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_order_order_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('address2', models.TextField()),
                ('area', models.TextField()),
                ('district', models.TextField()),
                ('City', models.TextField()),
                ('State', models.TextField()),
                ('Pin_Code', models.IntegerField()),
                ('default', models.BooleanField(default=False)),
                ('last_update', models.DateTimeField(default=datetime.datetime.now)),
                ('phone_number', models.CharField(max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
