# Generated by Django 3.2.12 on 2023-01-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_billaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ORDER_STATUS',
            field=models.CharField(choices=[('IN_PROGRESS', 'IN_PROGRESS'), ('CANCELLED', 'CANCELLED'), ('SHIPPED', 'SHIPPED'), ('ACCEPTED', 'ACCEPTED'), ('NOT_CREATED', 'NOT_CREATED')], default='NOT_CREATED', max_length=15),
        ),
    ]
